name: Run Cypress tests
on:
  pull_request:

  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Cypress tests in headless mode
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
